// Type Imports
import type { CourseType } from '@/types/apps/courseTypes'

export const db: CourseType[] = [
  {
    id: 1,
    title: 'Mini Game Tết 2025 - Lắc Lì Xì nhận quà khủng',
    category: 'Facebook',
    categoryClass: 'primary',
    image: '/images/courses/course-1.jpg',
    lesson: 7,
    ratingAve: 4.8,
    ratingCount: 156,
    author: 'Facebook VN',
    authorAvatar: '/images/avatars/1.png',
    videoUrl: 'a-CEyHSNrx0',
    price: 0,
    oldPrice: 0,
    status: 'active',
    featured: true,
    createdAt: '2025-12-01'
  },
  {
    id: 2,
    title: 'TikTok Shop - Săn deal 1K nhận voucher giảm giá',
    category: 'TikTok',
    categoryClass: 'info',
    image: '/images/courses/course-2.jpg',
    lesson: 5,
    ratingAve: 4.7,
    ratingCount: 203,
    author: 'TikTok',
    authorAvatar: '/images/avatars/2.png',
    videoUrl: 'a-CEyHSNrx0',
    price: 0,
    oldPrice: 0,
    status: 'active',
    featured: true,
    createdAt: '2025-12-02'
  },
  {
    id: 3,
    title: 'Zalo Pay - Quay số trúng thưởng tiền mặt',
    category: 'Zalo',
    categoryClass: 'success',
    image: '/images/courses/course-3.jpg',
    lesson: 10,
    ratingAve: 4.9,
    ratingCount: 89,
    author: 'Zalo',
    authorAvatar: '/images/avatars/3.png',
    videoUrl: 'dDTWCbtAh2Y',
    price: 0,
    oldPrice: 0,
    status: 'active',
    featured: false,
    createdAt: '2025-12-03'
  },
  {
    id: 4,
    title: 'Shopee Lắc Xu - Nhận xu miễn phí mỗi ngày',
    category: 'Shopee',
    categoryClass: 'error',
    image: '/images/courses/course-4.jpg',
    lesson: 14,
    ratingAve: 4.6,
    ratingCount: 178,
    author: 'Shopee',
    authorAvatar: '/images/avatars/4.png',
    videoUrl: 'lvYM9tHRz0M',
    price: 0,
    oldPrice: 0,
    status: 'active',
    featured: true,
    createdAt: '2025-12-04'
  },
  {
    id: 5,
    title: 'Lazada Game - Chơi game nhận voucher giảm giá',
    category: 'Lazada',
    categoryClass: 'primary',
    image: '/images/courses/course-5.jpg',
    lesson: 21,
    ratingAve: 4.8,
    ratingCount: 234,
    author: 'Lazada',
    authorAvatar: '/images/avatars/5.png',
    videoUrl: 'ybTdykZpbII',
    price: 0,
    oldPrice: 0,
    status: 'active',
    featured: false,
    createdAt: '2025-12-05'
  },
  {
    id: 6,
    title: 'MoMo Lắc Xì - Lắc điện thoại nhận lì xì',
    category: 'MoMo',
    categoryClass: 'warning',
    image: '/images/courses/course-6.jpg',
    lesson: 3,
    ratingAve: 4.5,
    ratingCount: 145,
    author: 'MoMo',
    authorAvatar: '/images/avatars/6.png',
    videoUrl: 'Egy-jJUNJ3A',
    price: 0,
    oldPrice: 0,
    status: 'inactive',
    featured: false,
    createdAt: '2025-12-06'
  }
]
